no-permission: "&cУ вас не достаточно прав!"
not-int: "&cВведёное вами число не является целым числом!"
send-money: "&aВы отправили игроку %name% на баланс %amount%"
accept-money: "&aВам отправил игрок %name% на баланс %amount%"
positive-number: "&cВведите положительное число!"
above-zero: "&cВведите число больше нуля!"
above-your-balance: "&cВы не можете отправить больше чем у вас есть на балансе!"
above-balance: "&cВы не можете отнять большем чем есть на балансе игрока!"
take-sender: "&aВы отняли у %name% с баланса %amount%"
take-target: "&aУ вас отняли %amount% с баланса!"
give-sender: "&aВы выдали игроку %name% на баланс %amount%"
your-balance: "&aВаш баланс: %amount%"
player-balance: "&aБаланс игрока: %amount%"
give-target: "&aВам выдали %amount%"
set-sender: "&aВы установили баланс игроку %name% на %amount%"
set-target: "&aВам установили баланс на %amount%"
invalid-player: "&cИгрок не в сети!"
new-balance: "&aВаш новый баланс: %balance%"
not-player: "&cИспользуйте данную команду от имени игрока!"